FROM solr:8

# Copy solr config from the version used by eZ Platform
COPY vendor/ibexa/solr/src/lib/Resources/config/solr/ /opt/solr/server/tmp

# Copy custom config files
COPY vendor/ibexa/solr/src/lib/Resources/config/solr/schema.xml /opt/solr/server/ezcloud/template/
COPY vendor/ibexa/solr/src/lib/Resources/config/solr/custom-fields-types.xml /opt/solr/server/ezcloud/template/
COPY vendor/ibexa/solr/src/lib/Resources/config/solr/language-fieldtypes.xml /opt/solr/server/ezcloud/template/

# Prepare config
USER root
RUN cp /opt/solr/server/solr/configsets/basic_configs/conf/solrconfig.xml /opt/solr/server/ezcloud/template/ \
 && cp /opt/solr/server/solr/configsets/basic_configs/conf/stopwords.txt /opt/solr/server/ezcloud/template/ \
 && cp /opt/solr/server/solr/configsets/basic_configs/conf/synonyms.txt /opt/solr/server/ezcloud/template/ \
 && cp /opt/solr/server/solr/solr.xml /opt/solr/server/ezcloud \
 && sed -i.bak '/<updateRequestProcessorChain name="add-unknown-fields-to-the-schema">/,/<\/updateRequestProcessorChain>/d' /opt/solr/server/ezcloud/template/solrconfig.xml \
 && sed -ie 's/${solr.autoSoftCommit.maxTime:-1}/${solr.autoSoftCommit.maxTime:20}/' /opt/solr/server/ezcloud/template/solrconfig.xml

USER solr

# Set our core config as home
ENV SOLR_HOME /opt/solr/server/ezcloud

# Make sure core is created on startup
CMD ["bash", "-c", "\
  solr-create -c core0 -d /opt/solr/server/ezcloud/template && \
  solr-create -c core1 -d /opt/solr/server/ezcloud/template && \
  solr-create -c core2 -d /opt/solr/server/ezcloud/template && \
  solr-create -c core3 -d /opt/solr/server/ezcloud/template && \
  solr-create -c core4 -d /opt/solr/server/ezcloud/template && \
  solr-create -c core5 -d /opt/solr/server/ezcloud/template && \
  solr-foreground \
"]