# Elastic config, to be appended after base-prod or base-dev, ..., but before selenium.yml
#
# NOTE: You'll need to manually run the command: php bin/console ibexa:elasticsearch:put-index-template.

services:
  app:
    depends_on:
      - elasticsearch
    environment:
      - SEARCH_ENGINE=elasticsearch
      - ELASTICSEARCH_DSN=elasticsearch:9200

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.19.22
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    networks:
      - frontend
      - backend
