version: '3.3'
# Multi-host setup for behat tests

services:
  web:
    command: /bin/bash -c "cd /var/www && cp -a doc/nginx/ez_params.d /etc/nginx && bin/vhost.sh --host-name=site.example.com --host-alias='*.local test4.local/eng test4.local/pol test4.local/fre test4.local/ger test4.local/ita test4.local/esl test4.local/por test4.local/ukr test4.local/swe test4.local/nor test4.local/fin test4.local/dan test4.local/hun test4.local/jpn test4.local/kor test4.local/cro test4.local/tur test4.local/rus test4.local/ser test3.local/eng test3.local/pol test3.local/fre test3.local/ger test3.local/ita test3.local/esl test3.local/por test3.local/ukr test3.local/swe test3.local/nor test3.local/fin test3.local/dan test3.local/hun test3.local/jpn test3.local/kor test3.local/cro test3.local/tur test3.local/rus test3.local/ser test2.local/eng test2.local/pol test2.local/fre test2.local/ger test2.local/ita test2.local/esl test2.local/por test2.local/ukr test2.local/swe test2.local/nor test2.local/fin test2.local/dan test2.local/hun test2.local/jpn test2.local/kor test2.local/cro test2.local/tur test2.local/rus test2.local/ser test1.local/eng test1.local/pol test1.local/fre test1.local/ger test1.local/ita test1.local/esl test1.local/por test1.local/ukr test1.local/swe test1.local/nor test1.local/fin test1.local/dan test1.local/hun test1.local/jpn test1.local/kor test1.local/cro test1.local/tur test1.local/rus test1.local/ser test0.local/eng test0.local/pol test0.local/fre test0.local/ger test0.local/ita test0.local/esl test0.local/por test0.local/ukr test0.local/swe test0.local/nor test0.local/fin test0.local/dan test0.local/hun test0.local/jpn test0.local/kor test0.local/cro test0.local/tur test0.local/rus test0.local/ser admin.example.com test.example.com' --template-file=doc/nginx/vhost.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    networks:
      frontend:
        aliases:
        # Multihost aliases
          - site.example.com
          - admin.example.com
          - test.example.com
        # SiteFactory aliases
          - test0.local
          - test1.local
          - test2.local
          - test3.local
          - test4.local
          - test5.local
          - test6.local
          - test7.local
          - test8.local
          - test9.local
          - test4.local/eng
          - test4.local/pol
          - test4.local/fre
          - test4.local/ger
          - test4.local/ita
          - test4.local/esl
          - test4.local/por
          - test4.local/ukr
          - test4.local/swe
          - test4.local/nor
          - test4.local/fin
          - test4.local/dan
          - test4.local/hun
          - test4.local/jpn
          - test4.local/kor
          - test4.local/cro
          - test4.local/tur
          - test4.local/rus
          - test4.local/ser
          - test3.local/eng
          - test3.local/pol
          - test3.local/fre
          - test3.local/ger
          - test3.local/ita
          - test3.local/esl
          - test3.local/por
          - test3.local/ukr
          - test3.local/swe
          - test3.local/nor
          - test3.local/fin
          - test3.local/dan
          - test3.local/hun
          - test3.local/jpn
          - test3.local/kor
          - test3.local/cro
          - test3.local/tur
          - test3.local/rus
          - test3.local/ser
          - test2.local/eng
          - test2.local/pol
          - test2.local/fre
          - test2.local/ger
          - test2.local/ita
          - test2.local/esl
          - test2.local/por
          - test2.local/ukr
          - test2.local/swe
          - test2.local/nor
          - test2.local/fin
          - test2.local/dan
          - test2.local/hun
          - test2.local/jpn
          - test2.local/kor
          - test2.local/cro
          - test2.local/tur
          - test2.local/rus
          - test2.local/ser
          - test1.local/eng
          - test1.local/pol
          - test1.local/fre
          - test1.local/ger
          - test1.local/ita
          - test1.local/esl
          - test1.local/por
          - test1.local/ukr
          - test1.local/swe
          - test1.local/nor
          - test1.local/fin
          - test1.local/dan
          - test1.local/hun
          - test1.local/jpn
          - test1.local/kor
          - test1.local/cro
          - test1.local/tur
          - test1.local/rus
          - test1.local/ser
          - test0.local/eng
          - test0.local/pol
          - test0.local/fre
          - test0.local/ger
          - test0.local/ita
          - test0.local/esl
          - test0.local/por
          - test0.local/ukr
          - test0.local/swe
          - test0.local/nor
          - test0.local/fin
          - test0.local/dan
          - test0.local/hun
          - test0.local/jpn
          - test0.local/kor
          - test0.local/cro
          - test0.local/tur
          - test0.local/rus
          - test0.local/ser
      backend:
        aliases:
        # Multihost aliases
          - site.example.com
          - admin.example.com
          - test.example.com
        # SiteFactory aliases
          - test0.local
          - test1.local
          - test2.local
          - test3.local
          - test4.local
          - test5.local
          - test6.local
          - test7.local
          - test8.local
          - test9.local
          - test4.local/eng
          - test4.local/pol
          - test4.local/fre
          - test4.local/ger
          - test4.local/ita
          - test4.local/esl
          - test4.local/por
          - test4.local/ukr
          - test4.local/swe
          - test4.local/nor
          - test4.local/fin
          - test4.local/dan
          - test4.local/hun
          - test4.local/jpn
          - test4.local/kor
          - test4.local/cro
          - test4.local/tur
          - test4.local/rus
          - test4.local/ser
          - test3.local/eng
          - test3.local/pol
          - test3.local/fre
          - test3.local/ger
          - test3.local/ita
          - test3.local/esl
          - test3.local/por
          - test3.local/ukr
          - test3.local/swe
          - test3.local/nor
          - test3.local/fin
          - test3.local/dan
          - test3.local/hun
          - test3.local/jpn
          - test3.local/kor
          - test3.local/cro
          - test3.local/tur
          - test3.local/rus
          - test3.local/ser
          - test2.local/eng
          - test2.local/pol
          - test2.local/fre
          - test2.local/ger
          - test2.local/ita
          - test2.local/esl
          - test2.local/por
          - test2.local/ukr
          - test2.local/swe
          - test2.local/nor
          - test2.local/fin
          - test2.local/dan
          - test2.local/hun
          - test2.local/jpn
          - test2.local/kor
          - test2.local/cro
          - test2.local/tur
          - test2.local/rus
          - test2.local/ser
          - test1.local/eng
          - test1.local/pol
          - test1.local/fre
          - test1.local/ger
          - test1.local/ita
          - test1.local/esl
          - test1.local/por
          - test1.local/ukr
          - test1.local/swe
          - test1.local/nor
          - test1.local/fin
          - test1.local/dan
          - test1.local/hun
          - test1.local/jpn
          - test1.local/kor
          - test1.local/cro
          - test1.local/tur
          - test1.local/rus
          - test1.local/ser
          - test0.local/eng
          - test0.local/pol
          - test0.local/fre
          - test0.local/ger
          - test0.local/ita
          - test0.local/esl
          - test0.local/por
          - test0.local/ukr
          - test0.local/swe
          - test0.local/nor
          - test0.local/fin
          - test0.local/dan
          - test0.local/hun
          - test0.local/jpn
          - test0.local/kor
          - test0.local/cro
          - test0.local/tur
          - test0.local/rus
          - test0.local/ser
