FROM ibexa_php:latest

# Install Node.js and Yarn
RUN apt-get update -y \
    && apt-get install -y --no-install-recommends \
        ca-certificates curl xz-utils \
    \
    && curl -fsSL https://nodejs.org/dist/v12.22.12/node-v12.22.12-linux-x64.tar.xz \
        | tar -xJ -C /usr/local --strip-components=1 \
    \
    && node -v \
    && npm -v \
    \
    && npm install -g yarn@1.22.19 \
    \
    && rm -rf /var/lib/apt/lists/*
