FROM ibexa_php:latest

# Install Node.js and Yarn
RUN apt-get update -y \
    && apt-get install -y --no-install-recommends \
        ca-certificates curl gnupg \
    \
    && curl -fsSL https://deb.nodesource.com/setup_18.x | bash - \
    && apt-get install -y nodejs \
    \
    && corepack enable \
    && corepack prepare yarn@1.22.22 --activate \
    \
    && rm -rf /var/lib/apt/lists/*
